namespace WebAppHF.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class insertJazz : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Gumbo Kings', '20180726','06:00PM', '07:00PM', 'Patronaat', 1500, 'Zijlsingel 2, 2013 DN Haarlem', 300, 'Main Hall', 'Gumbo Kings', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Evolve', '20180726','07:30PM', '08:30PM', 'Patronaat', 1500, 'Zijlsingel 2, 2013 DN Haarlem', 300, 'Main Hall', 'Evolve', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Ntjam Rosie', '20180726','09:00PM', '10:00PM', 'Patronaat', 1500, 'Zijlsingel 2, 2013 DN Haarlem', 300, 'Main Hall', 'Ntjam Rosie', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Wicked Jazz Sounds', '20180726','06:00PM', '07:00PM', 'Patronaat', 1000, 'Zijlsingel 2, 2013 DN Haarlem', 200, 'Second Hall', 'Wicked Jazz Sounds', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Tom Thomsom Assemble', '20180726','07:30PM', '08:30PM', 'Patronaat', 1000, 'Zijlsingel 2, 2013 DN Haarlem', 200, 'Second Hall', 'Tom Thomsom Assemble', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Jonna Frazer', '20180726','09:00PM', '10:00PM', 'Patronaat', 1000, 'Zijlsingel 2, 2013 DN Haarlem', 200, 'Second Hall', 'Jonna Frazer', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Fox & The Mayors', '20180727','06:00PM', '07:00PM', 'Patronaat', 1500, 'Zijlsingel 2, 2013 DN Haarlem', 300, 'Main Hall', 'Fox & The Mayors', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Uncle Sue', '20180727','07:30PM', '08:30PM', 'Patronaat', 1500, 'Zijlsingel 2, 2013 DN Haarlem', 300, 'Main Hall', 'Uncle Sue', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Chris Allen', '20180727','09:00PM', '10:00PM', 'Patronaat', 1500, 'Zijlsingel 2, 2013 DN Haarlem', 300, 'Main Hall', 'Chris Allen', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Myles Sanko', '20180727','06:00PM', '07:00PM', 'Patronaat', 1000, 'Zijlsingel 2, 2013 DN Haarlem', 200, 'Second Hall', 'Myles Sanko', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Ruis Soundsystem', '20180727','07:30PM', '08:30PM', 'Patronaat', 1000, 'Zijlsingel 2, 2013 DN Haarlem', 200, 'Second Hall', 'Ruis Soundsystem', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','The Family XL', '20180727','09:00PM', '10:00PM', 'Patronaat', 1000, 'Zijlsingel 2, 2013 DN Haarlem', 200, 'Second Hall', 'The Family XL', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Gare du Nord', '20180728','06:00PM', '07:00PM', 'Patronaat', 1500, 'Zijlsingel 2, 2013 DN Haarlem', 300, 'Main Hall', 'Gare du Nord', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Rilan & The Bombadiers', '20180728','07:30PM', '08:30PM', 'Patronaat', 1500, 'Zijlsingel 2, 2013 DN Haarlem', 300, 'Main Hall', 'Rilan & The Bombadiers', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Soul Six', '20180728','09:00PM', '10:00PM', 'Patronaat', 1500, 'Zijlsingel 2, 2013 DN Haarlem', 300, 'Main Hall', 'Soul Six', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Han Bennink', '20180728','06:00PM', '07:00PM', 'Patronaat', 1000, 'Zijlsingel 2, 2013 DN Haarlem', 150, 'Third Hall', 'Han Bennink', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','The Nordanians', '20180728','07:30PM', '08:30PM', 'Patronaat', 1000, 'Zijlsingel 2, 2013 DN Haarlem', 150, 'Third Hall', 'The Nordanians', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Lilith Merlot', '20180728','09:00PM', '10:00PM', 'Patronaat', 1000, 'Zijlsingel 2, 2013 DN Haarlem', 150, 'Third Hall', 'Lilith Merlot', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Ruis Soundsystem', '20180729','03:00PM', '04:00PM', 'Grote Markt', 0, 'Grote Markt, 2011 Haarlem', 0, 'Outside', 'Ruis Soundsystem', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Wicked Jazz Sounds', '20180729','04:00PM', '05:00PM', 'Grote Markt', 0, 'Grote Markt, 2011 Haarlem', 0, 'Outside', 'Wicked Jazz Sounds', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Evolve', '20180729','05:00PM', '06:00PM', 'Grote Markt', 0, 'Grote Markt, 2011 Haarlem', 0, 'Outside', 'Evolve', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','The Nordanians', '20180729','06:00PM', '07:00PM', 'Grote Markt', 0, 'Grote Markt, 2011 Haarlem', 0, 'Outside', 'The Nordanians', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Gumbo Kings', '20180729','07:00PM', '08:00PM', 'Grote Markt', 0, 'Grote Markt, 2011 Haarlem', 0, 'Outside', 'Gumbo Kings', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Gare du Nord', '20180729','08:00PM', '09:00PM', 'Grote Markt', 0, 'Grote Markt, 2011 Haarlem', 0, 'Outside', 'Gare du Nord', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Pass-Partout', '20180726','06:00PM', '10:00PM', 'Patronaat', 3500, 'Zijlsingel 2, 2013 DN Haarlem', 0, 'Main & Second Hall', 'Pass-Partout 26-12', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Pass-Partout', '20180727','06:00PM', '10:00PM', 'Patronaat', 3500, 'Zijlsingel 2, 2013 DN Haarlem', 0, 'Main & Second Hall', 'Pass-Partout 27-12', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Pass-Partout', '20180728','06:00PM', '10:00PM', 'Patronaat', 3500, 'Zijlsingel 2, 2013 DN Haarlem', 0, 'Main & Third Hall', 'Pass-Partout 28-12', '/IMG/#') " +
"INSERT INTO EVENTS (DISCRIMINATOR, NAME, DATE, STARTTIME, ENDTIME, LOCATIONNAME, PRICE, ADRESS, SEATSAVAILABLE, HALL, BAND, IMGSTRING) VALUES ('JAZZ','Pass-Partout', '20180726','06:00PM', '10:00PM', 'Patronaat', 8000, 'Grote Markt, 2011 Haarlem', 0, 'Main, Second & Third Hall', 'Pass-Partout 26 t/m 28-12', '/IMG/#') "
);
        }
        
        public override void Down()
        {
        }
    }
}
